create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
create table aeroporto (cidade_id bigint, id bigserial not null, codigo_iata varchar(255), nome varchar(255), primary key (id));
create table bagagem (id bigserial not null, passagem_id bigint, primary key (id));
create table cidade (id bigserial not null, nome varchar(255), uf varchar(255), primary key (id));
create table classe (qtd_assentos integer, valor numeric(38,2), id bigserial not null, voo_id bigint, tipo varchar(255), primary key (id));
create table comprador (data_nascimento date, id bigserial not null, cpf varchar(255), email varchar(255), nome varchar(255), primary key (id));
create table passageiro (data_nascimento date, id bigserial not null, cpf varchar(255), nome varchar(255), primary key (id));
create table passagem (cancelada boolean, despacho_bagagem boolean, number integer, preco numeric(38,2), classe_id bigint unique, comprador_id bigint, id bigserial not null, passageiro_id bigint unique, primary key (id));
create table voo (cancelado boolean, number integer, aeroporto_destino_id bigint, aeroporto_origem_id bigint, id bigserial not null, primary key (id));
alter table if exists aeroporto add constraint FKhv1yxhbmq8k2uykh34we5wwjx foreign key (cidade_id) references cidade;
alter table if exists bagagem add constraint FKq2u2mgi52bb1nypyxdxt1e2pr foreign key (passagem_id) references passagem;
alter table if exists classe add constraint FKip6x9pbmhnqsapal95s0q086t foreign key (voo_id) references voo;
alter table if exists passagem add constraint FKdr09f7srr6jkk65ojwm2bvygj foreign key (classe_id) references classe;
alter table if exists passagem add constraint FKlwpvecgq6fyt4rd8w8c5451wu foreign key (comprador_id) references comprador;
alter table if exists passagem add constraint FKebde0l4nuqgru03ocnfvnw6ip foreign key (passageiro_id) references passageiro;
alter table if exists voo add constraint FKsevme5ini9b39q1nm90x99qfh foreign key (aeroporto_destino_id) references aeroporto;
alter table if exists voo add constraint FKeu73jnyakkgqutigsgv9ysrbu foreign key (aeroporto_origem_id) references aeroporto;
INSERT INTO cidade (id, nome, uf) VALUES (1, "Salvador", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (2, "Feira de Santana", "BA");
INSERT INTO cidade (id, nome, uf) VALUES (3, "São Paulo", "SP");
INSERT INTO cidade (id, nome, uf) VALUES (4, "Rio de Janeiro", "RJ");
INSERT INTO cidade (id, nome, uf) VALUES (5, "Gramado", "RS");
INSERT INTO cidade (id, nome, uf) VALUES (6, "Recife", "PE");
INSERT INTO cidade (id, nome, uf) VALUES (7, "Olinda", "PE");
